name: Setup Python with uv
description: Install uv, set up Python, and install project dependencies

runs:
  using: composite
  steps:
    - name: Restore .venv cache
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python 3.14t (free-threaded build)
      shell: bash
      run: uv python install
      # Uses version from .python-version (3.14t = free-threaded build)

    - name: Install dependencies
      shell: bash
      run: uv sync --frozen
